string name
int32 id
float64 timestamp

geometry_msgs/Vector3 lin_acc
geometry_msgs/Vector3 lin_vel
geometry_msgs/Vector3 lin_pos

geometry_msgs/Vector3 ang_acc
geometry_msgs/Vector3 ang_vel
geometry_msgs/Vector3 euler
geometry_msgs/Vector3 euler_dot
geometry_msgs/Quaternion quaternion

uint32[] pwm
float64[] actuators
geometry_msgs/Vector3 force
geometry_msgs/Vector3 torque

geometry_msgs/Vector3 accelerometer
geometry_msgs/Vector3 gyroscope
geometry_msgs/Vector3 magnetometer
